### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tchangalov** [NCSU-Libraries/Suma-Vagrant#1]
Hello! Here is my issue:

![image](https://cloud.githubusercontent.com/assets/13037791/8337858/77625ebe-1a7b-11e5-9805-a580be082e80.png)

I am a student worker at the Engineering Library over at the University of Maryland, College Park. We are interested in incorporating this app. I don't have experience with yaml (the error file) and I've tried installing this demo development environment many different ways. The image shows the issue I'm running into. I have a feeling there's a glitch that makes it screw up on Windows. I've tried on two different machines (work laptop and personal laptop) and I run into the same issue.

The localhost loads, but none of the features work. I just get to an internal error when I try to use any of the admin configurations. I tried installing it with the Parallels provider as well, but it doesn't work. 

![image](https://cloud.githubusercontent.com/assets/13037791/8338047/7098f236-1a7c-11e5-9a29-1ea771d1cfca.png)

What should I try to do?

Thanks

**Comment by bretdavidson** [comment]
Thanks for your interest in this project. I've pushed a small change to the Vagrantfile that will use smb for the vagrant synced folder when the host is Windows. Please try recreating the VM using this change. Hopefully this will resolve the issue you are having, which I believe may be related to this issue: https://github.com/ansible/ansible/issues/9526

Please be aware that this Suma-Vagrant project is only supported as a demonstration instance at this time and is not recommended for production use. If you are interested in using Suma in production, please refer to the core Suma repository: https://github.com/cazzerson/Suma

Thanks!

Bret

**Comment by tchangalov** [comment]
Thank you so much! I'll try it all over as soon as possible. And yes, I'm developing the app first as a demo before they put it on the university servers. Again, thank you so much for replying and making the change for me.

-Ivo

**Comment by gbannerman** [comment]
Hi,

I'm getting this exact same issue with the error message that the text file is busy.

I'm running the most recent versions of VirtualBox and Vagrant on Windows 10 and I'm using the up to date version of the suma-vagrant project.

I can run the client in browser but get the same internal server error when accessing the admin tools.

Any help would be much appreciated!

**Comment by cazzerson** [comment]
Hi @GavinBannerman,

Could you please share the following info?

1) When did you first use Suma-Vagrant to create this virtual machine?
2) What specific versions of Vagrant and VirtualBox are you using?

@bretdavidson: this may be related to an Ansible issue.

https://github.com/ansible/ansible/issues/9526

Thanks,
Jason

**Comment by gbannerman** [comment]
@cazzerson 

1) I both cloned the suma-vagrant project and created the VM yesterday.

2) I am using: Vagrant v1.8.1 and VirtualBox v5.0.16

Thanks for your quick reply.

**Comment by cazzerson** [comment]
@GavinBannerman It's a bit of a shot in the dark, but I just pushed a change that I can't test due to lack of Windows. Could you give it a try? Just pull down the latest changes to Suma-Vagrant and run `vagrant destroy;vagrant up`

**Comment by cazzerson** [comment]
@GavinBannerman Sorry, just made one more change.

**Comment by gbannerman** [comment]
@cazzerson 

Tried again with your most recent changes and still getting that same error unfortunately. I've included a screen grab.
![suma-error](https://cloud.githubusercontent.com/assets/16233190/14121727/33d92834-f5be-11e5-8901-03daa49206eb.PNG)

**Comment by cazzerson** [comment]
@GavinBannerman I just pushed a couple more changes. Could you try again?

**Comment by gbannerman** [comment]
@cazzerson Thanks for all your help so far.

It's getting further in the set up process and isn't explicitly saying its failing, but I think there's another error. When I attempt to load localhost:19679, its not reaching the server. I've included a text dump of the debug output when I run 'vagrant up'. If you need any more details just let me know.

http://dumptext.com/kKSmeIwx#

![suma-error2](https://cloud.githubusercontent.com/assets/16233190/14165124/0145e0fc-f6cb-11e5-988b-2535c3f337d0.PNG)

**Comment by cazzerson** [comment]
@GavinBannerman Yeah, accidentally changed the port:-) Could you update again and run `vagrant reload`?

**Comment by gbannerman** [comment]
@cazzerson its working perfectly now, thanks a lot for your help!

**Comment by cazzerson** [comment]
@GavinBannerman Great! Thanks for your patience.
